### ISSUE TITLE
Error 404 on npm install

### ISSUE THREAD

**Issue by andreivictor** [fxpio/fxp-select2-responsive#1]
`npm install @fxp/select2-responsive --save`

throws the following error:
npm ERR! code E404
npm ERR! 404 Not found : @fxp/select2-responsive
npm ERR! 404 
npm ERR! 404  '@fxp/select2-responsive' is not in the npm registry.

**Comment by francoispluchino** [comment]
This package hasn't release because it is in development. With NPM, it's preferable to not registering the package in NPM Registry without first stable version, which was not the case of Bower. I must update the doc. So, you must use the git link.

Run this command:
```
$ npm install git+ssh://git@github.com/fxpio/fxp-select2-responsive.git#master --save
```

**Comment by francoispluchino** [comment]
You can also use the github alias:

```
$ npm install fxpio/fxp-jquery-ripple#master --save
```

or

```
$ npm install github:fxpio/fxp-jquery-ripple#master --save
```

**Comment by andreivictor** [comment]
Thanks for your reply.

Also, the idea of this plugin is very interesting, I have been looking for a long time for a solution to improve the UX of these select2 elements on responsive / touch devices.
